// coercion === auto type conversion    

console.log(`from number to string and boolean`);
console.log(`🚀🔥👉 ⚡ String(0)`, String(0));
console.log(`🚀🔥👉 ⚡ Boolean(0)`, Boolean(0));
console.log(`🚀🔥👉 ⚡ String(1)`, String(1));
console.log(`🚀🔥👉 ⚡ Boolean(1)`, Boolean(1));
console.log(`=============================`);
console.log(`from string to number and boolean`);
console.log(`🚀🔥👉 ⚡ Number("");`, Number(""));
console.log(`🚀🔥👉 ⚡ Boolean("");`, Boolean(""));
console.log(`🚀🔥👉 ⚡ Number("a");`, Number("a"));
console.log(`🚀🔥👉 ⚡ Boolean("a");`, Boolean("a"));
console.log(`🚀🔥👉 ⚡ Number("5");`, Number("5"));
console.log(`🚀🔥👉 ⚡ Boolean("5");`, Boolean("5"));
console.log(`=============================`);
console.log(`from boolean to string and number`);
console.log(`🚀🔥👉 ⚡ String(false)`, String(false));
console.log(`🚀🔥👉 ⚡ Number(false)`, Number(false));
console.log(`🚀🔥👉 ⚡ String(true)`, String(true));
console.log(`🚀🔥👉 ⚡ Number(true)`, Number(true));
console.log(`=============================`);
console.log(`null,undefined,NaN datatypes to string , number and boolean`);
console.log(`🚀🔥👉 ⚡ String(null)`, String(null));
console.log(`🚀🔥👉 ⚡ Number(null)`, Number(null));
console.log(`🚀🔥👉 ⚡ Boolean(null)`, Boolean(null));
console.log(`🚀🔥👉 ⚡ String(undefined)`, String(undefined));
console.log(`🚀🔥👉 ⚡ Number(undefined)`, Number(undefined));
console.log(`🚀🔥👉 ⚡ Boolean(undefined)`, Boolean(undefined));
console.log(`🚀🔥👉 ⚡ String(NaN)`, String(NaN));
console.log(`🚀🔥👉 ⚡ Number(NaN)`, Number(NaN));
console.log(`🚀🔥👉 ⚡ Boolean(NaN)`, Boolean(NaN));
console.log(`=============================`);
console.log(`arrays and objects to string ,number and boolean`);
console.log(`🚀🔥👉 ⚡ String([])`, String([]));
console.log(`🚀🔥👉 ⚡ Number([])`, Number([]));
console.log(`🚀🔥👉 ⚡ Boolean([])`, Boolean([]));
console.log(`🚀🔥👉 ⚡ String([1])`, String([1]));
console.log(`🚀🔥👉 ⚡ Number([1])`, Number([1]));
console.log(`🚀🔥👉 ⚡ Boolean([1])`, Boolean([1]));
console.log(`🚀🔥👉 ⚡ String([1, 2])`, String([1, 2]));
console.log(`🚀🔥👉 ⚡ Number([1, 2])`, Number([1, 2]));
console.log(`🚀🔥👉 ⚡ Boolean([1, 2])`, Boolean([1, 2]));
console.log(`🚀🔥👉 ⚡ String(['hel','lo'])`, String(['hel','lo']));
console.log(`🚀🔥👉 ⚡ Number(['hel','lo'])`, Number(['hel','lo']));
console.log(`🚀🔥👉 ⚡ Boolean(['hel','lo'])`, Boolean(['hel','lo']));
console.log(`🚀🔥👉 ⚡ String({})`, String({}));
console.log(`🚀🔥👉 ⚡ Number({})`, Number({}));
console.log(`🚀🔥👉 ⚡ Boolean({})`, Boolean({}));
